name: Execute On Push

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository Contents
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # Install latest python

      - name: Install 7-Zip
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full
          
      - name: Install Python Packages Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements
          
      - name: Execute Python Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          TELEGRAM_CHANNEL_HANDLE: ${{ secrets.TELEGRAM_CHANNEL_HANDLE }}
        run: python main.py
          
      - name: Commit Files
        run: |
          git config --local user.email "nonusernameaccount@protonmail.com"
          git config --local user.name "Unavailable User"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')" --allow-empty)

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TELEGRAM_TUNNEL_PUBLISHER }}
          branch: main
       
      - name: Clean Up Files
        run: |
          git checkout --orphan latest_branch
          git config --local user.email "nonusernameaccount@protonmail.com"
          git config --local user.name "Unavailable User"
          git add -A
          git commit -am "Updated $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M %Z')"
          git branch -D main
          git branch -m main
          git push -f origin main

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TELEGRAM_TUNNEL_PUBLISHER }}
          branch: main
